# This is a crate
name = "spdx_tool"
description = "SPDX Tool"
version = "0.1.0-dev"

authors = ["ciceron"]
maintainers = ["ciceron <Stephane.Carrez@gmail.com>"]
maintainers-logins = ["stcarrez"]
licenses = "Apache-2.0"
website = ""
tags = []

executables = ["spdx_tool"]

project-files = ["spdx_tool.gpr"]

[[depends-on]]
utilada = "^2.6.0"
utilada_xml = "^2.6.0"
sciada = "~0.2.0"
spdx = "~0.2.0"
ansiada = "^1.0.0"
intl = "^1.0.1"
printer_toolkitada = "~0.2.0"
ada_toml = "~0.3.0"

# [configuration]
# disabled = true

[depends-on."case(os)".linux]
magicada = "^1"

[depends-on."case(os)".freebsd]
magicada = "^1"

[gpr-set-externals."case(os)"]
linux = { USE_MAGICADA = "yes" }
freebsd = { USE_MAGICADA = "yes" }
macos = { USE_MAGICADA = "no" }
windows = { USE_MAGICADA = "no" }

[[pins]]
printer_toolkitada = { url="https://gitlab.com/stcarrez/printer-toolkit.git" }
sciada = { url="https://gitlab.com/stcarrez/ada-sci.git" }
utilada = { url="https://github.com/stcarrez/ada-util.git" }