name = "spdx_tool_tests"
description = "SPDX Tool unit tests"
version = "1.0.0"

authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
licenses = "Apache-2.0"
website = ""
tags = []

executables = ["spdx_tool_harness"]

[[depends-on]]
spdx_tool = "*"
utilada_unit = "^2.6.0"

[configuration]
disabled = true

[[pins]]
spdx_tool = { path='..' }

